###########################################
###   CONFIGURACIÓN OFICIAL HYPRSCROLLING  ###
###########################################

# Carga el plugin al inicio
exec-once = hyprpm reload -n

# Cambio a layout Scrolling
general {
    layout = scrolling
  }

plugin {
    hyprscrolling {
        # Activa el plugin
        active = true

        # Define qué tecla debes mantener para hacer el scroll.
        modifier = SUPER

        # Distancia en píxeles para cambiar de workspace.
        # Si pones 500, tendrás que mover mucho la rueda. 200 es lo ideal.
        #distance = 200

        # Dirección del scroll:
        # false = scroll abajo -> siguiente workspace
        # true = scroll arriba -> siguiente workspace (estilo natural)
       # reverse = false

        follow_focus = true

               # Width of each column as fraction of monitor width
        column_width = 0.8

        #If only one column exists, make it fullscreen?
        fullscreen_on_one_column = true

        #Custom column widths for cycling with +conf / -conf
        explicit_column_widths = 0.333, 0.5, 0.667, 1.0

        #When focusing, center or fit? (0=center, 1=fit)
        focus_fit_method = 1
    }
}

###########################################
###    BINDINGS COMPATIBLES (Tus Keys)  ###
###########################################

# Para moverte entre workspaces con el teclado (usando tus teclas , y .)
bind = $mainMod, period, layoutmsg, move +col
bind = $mainMod, comma, layoutmsg, move -col

# Para mover la ventana actual al workspace de al lado

bind = $mainMod SHIFT, period, layoutmsg, movewindowto r
bind = $mainMod SHIFT, comma, layoutmsg, movewindowto l
bind = $mainMod SHIFT, up, layoutmsg, movewindowto u
bind = $mainMod SHIFT, down, layoutmsg, movewindowto d

