
# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝
# -------------------------------------------------------------------



################
### MONITORS ###
################
source = /home/rinooze/.config/hypr/Shell/monitors.conf


###################
### MY PROGRAMS ###
###################
source = /home/rinooze/.config/hypr/Shell/programs.conf


#################
### AUTOSTART ###
#################
source = /home/rinooze/.config/hypr/Shell/autostart.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################
source = /home/rinooze/.config/hypr/Shell/environment.conf


#####################
### LOOK AND FEEL ###
#####################
source = /home/rinooze/.config/hypr/Shell/appearance.conf
source = /home/rinooze/.config/hypr/Shell/animation.conf
source = /home/rinooze/.config/hypr/Shell/layout.conf



#############
### INPUT ###
#############
source = /home/rinooze/.config/hypr/Shell/input.conf


###################
### KEYBINDINGS ###
###################
source = /home/rinooze/.config/hypr/Shell/keybindings.conf


####################
### WINDOWRULES AND WORSPACES ###
####################
source = /home/rinooze/.config/hypr/Shell/windowrule.conf

###################
### PLUGINS #######
###################
source = /home/rinooze/.config/hypr/Shell/plugins.conf
#source = /home/rinooze/.config/hypr/hyprscrolling.conf
