#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = nm-applet &

#exec-once = waypaper --restore
#exec-once = swww-daemon
#exec-once = hyprpaper
exec-once = swaync &
exec-once = GDK_BACKEND=x11 DISPLAY=:0 snixembed --fork
exec-once = swayosd-server
exec-once = waybar

exec-once = hyprpaper
exec-once = sleep 1 && hyprctl hyprpaper wallpaper ",$(cat ~/.cache/hyprpaper-last)"


#exec-once = ~/.config/hypr/start-dock.sh
#exec-once = eww daemon && eww open widgets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hyprpm reload -n
