#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = $terminal
exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox
#exec-once = rofi

#exec-once = rofi
exec-once = waybar
exec-once = waypaper --restore
exec-once = swww-daemon
exec-once = swaync &
exec-once = snixembed --fork
exec-once = swayosd-server

#exec-once = hyprpaper
exec-once = ~/.config/hypr/start-dock.sh
#exec-once = eww daemon && eww open widgets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hyprpm reload -n
