# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
general {
    layout = scrolling
}

dwindle {
     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
     preserve_split = true # You probably want this
 }

scrolling {
    # Una sola columna ocupa toda la pantalla
    fullscreen_on_one_column = true

    # Ancho por defecto de columnas [0.1 - 1.0]
    column_width = 0.5

    # Cómo traer una columna a la vista al enfocarla
    # 0 = centrar | 1 = ajustar
    focus_fit_method = 1

    # Mover automáticamente la vista al enfocar una ventana
    follow_focus = true

    # Fracción mínima visible para que el foco siga [0.0 - 1.0]
    follow_min_visible = 0.4

    # Anchos predefinidos para redimensionar columnas
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0

    # Dirección en que aparecen nuevas ventanas
    # opciones: left | right | down | up
    direction = right
}

# monocle {
#
#
# }

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 0
    vfr = true
}


