# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
general {
    layout = scrolling
}

dwindle {
     pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
     preserve_split = true # You probably want this
 }

scrolling {
    fullscreen_on_one_column = true
    column_width = 0.5
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 0.4
    explicit_column_widths = 0.333, 0.5, 0.667, 1.0
    direction = right
}

# monocle {
# }

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    vrr = 0
    vfr = true
}


