[files]
current_page=12
recent_files=/home/rinooze/Downloads/shell.qml;/home/rinooze/.config/record-selector/record.sh;/home/rinooze/Downloads/shell(1).qml;/home/rinooze/Downloads/zshrc(1);/home/rinooze/Downloads/zshrc;/home/rinooze/Downloads/config.jsonc;/home/rinooze/.config/waybar/themes/pastel-dream.css;/home/rinooze/albiononline/uninstall-albiononline.sh;/home/rinooze/Downloads/shell(8).qml;/home/rinooze/Downloads/shell(7).qml;
recent_projects=
FILE_NAME_0=1230;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Fhypr%2FShell%2Fkeybindings.conf;0;4
FILE_NAME_1=3791;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Fhypr%2FShell%2Fwindowrule.conf;0;4
FILE_NAME_2=493;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Fhypr%2FShell%2Fautostart.conf;0;4
FILE_NAME_3=0;Sh;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Frofi%2Frofi-bluetooth.sh;0;4
FILE_NAME_4=992;None;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Frofi%2Fnetwork.rasi;0;4
FILE_NAME_5=193;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Fhypr%2FShell%2Fmonitors.conf;0;4
FILE_NAME_6=271;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Fhypr%2FShell%2Fenvironment.conf;0;4
FILE_NAME_7=493;None;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2FDownloads%2Fbluetooth.rasi;0;4
FILE_NAME_8=0;None;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2FDownloads%2Fconfig.jsonc;0;4
FILE_NAME_9=0;Conf;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2FDownloads%2Fzshrc;0;4
FILE_NAME_10=0;None;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2FDownloads%2Fzshrc%281%29;0;4
FILE_NAME_11=5400;Sh;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2F.config%2Frecord-selector%2Frecord.sh;0;4
FILE_NAME_12=0;None;0;EUTF-8;1;1;0;%2Fhome%2Frinooze%2FDownloads%2Fshell.qml;0;4

[project]
session_file=
project_file_path=/home/rinooze/projects

[geany]
treeview_position=153
msgwindow_position=787
geometry=0;0;949;1019;1;
sidebar_page=0

[search]
find_all_expanded=false
replace_all_expanded=false
position_find_x=-1
position_find_y=-1
position_replace_x=-1
position_replace_y=-1
position_fif_x=-1
position_fif_y=-1

[plugins]
load_plugins=true
custom_plugin_path=
active_plugins=;

[VTE]
last_dir=/home/rinooze
